### ISSUE TITLE
Feature: Automate End-to-End Testing

### ISSUE THREAD

**Issue by bushidocodes** [gwsystems/sledge-serverless-framework#136]
There are different sample applications and tests that can be run to check for regressions

- ekf - gps workload
- ocr - fivebyeight
- ocr - handwriting
- ocr - hyde
- cmsis_nn - image classification
- cmsis_nn - image resize
- cmsis_nn - license plate detection

Each of these tests need to be run separately, but these should be run via a single script or Makefile command.

This could optionally also be implemented as a GitHub Actions CI workflow.

**Comment by emil916** [comment]
There seems to be a slight mistake?
*sod - image resize
*sod - license plate detection
