### ISSUE TITLE
Upgrade clang in the Dockerfile from 8 to the latest version

### ISSUE THREAD

**Issue by emil916** [gwsystems/sledge-serverless-framework#156]
Upgrade both in x86 and aarch64

https://github.com/gwsystems/sledge-serverless-framework/blob/e2ce8398dcb454f2a4c6da1a00c9f460198922a5/Dockerfile.x86_64#L20

**Comment by bushidocodes** [comment]
Resolved by #179. Technically, we're still pinned to clang-8 due to a the llvm bindings used by awsm, but sledge can uses a configurable version of LLVM tools, so this is now a single parameter we can change from 8 to 11 when this gets unblocked.
