### ISSUE TITLE
Unit and system test regime

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/sledge-serverless-framework#23]
We need a test regime, at the very least, for unit test and system test for when we do PRs, we both extend the test cases and test all the prior ones that are still applicable.

How to? I think we have a few test programs in runtime/test, like, FILE I/O, SOCKET I/O, FIBONACCI etc, perhaps we start from there? 
We might also need to test a couple of things here,
1. WASM features that we add or modify, we'd need to test those. 
2. SERVERLESS functionality
3. Unit testing could be around: http request/response, different wasm modules with different memory/stack/other requirements, scheduling, timeouts, preemptions, JSON configurations, etc.

@bushidocodes You have changed a lot, though it is changing naming, cleaning up unused code, outdated documentation, etc and not functionality changes I think, it would be good to write in the PRs what you tested!!

**Comment by bushidocodes** [comment]
Closing in favor of #136
