### ISSUE TITLE
Bug: sandbox alloc doesn't actually allocate based on sandbox struct size

### ISSUE THREAD

**Issue by bushidocodes** [gwsystems/sledge-serverless-framework#347]
![image](https://user-images.githubusercontent.com/8700322/171752388-8b365808-11fc-4e3a-866c-febbd4d15aaa.png)

**Comment by bushidocodes** [comment]
@emil916 - I don't recall why we opened this. This looks like to me. We're rounding up to the nearest page and aligning on pages. Am I missing something?

**Comment by emil916** [comment]
I think this was reported by Xiaosu. It should have been sizeof(struct sandbox)). Just checked, it has been fixed since then. So, we can close the issue.
