### ISSUE TITLE
Setting up a development environment

### ISSUE THREAD

**Issue by YlqyY** [gwsystems/sledge-serverless-framework#371]
Ignored:1 https://apt.llvm.org/jammy llvm-toolchain-jammy-12 InRelease Error:6 https://apt.llvm.org/jammy llvm-toolchain-jammy-12 Release 404 Not Found [IP: 151.101.42.49 443] Reading package list... Done E: The repository "http://apt.llvm.org/jammy llvm-toolchain-jammy-12 Release" does not have a Release file. N: It is not possible to safely update with this source, so it is disabled by default. N: See the apt-secure(8) manual for details on repository creation and user configuration. 
Do the errors that appear above have any impact on the commands that follow? Looking forward to your help, thanks!

**Comment by emil916** [comment]
Hi! Thanks for raising the issue! Looks critical to me.

Can you please elaborate on what exactly you were trying to do (set up on Debian or docker) and at which step the above error actually occurred?

**Comment by YlqyY** [comment]
> Hi! Thanks for raising the issue! Looks critical to me.
> 
> Can you please elaborate on what exactly you were trying to do (set up on Debian or docker) and at which step the above error actually occurred?

Thanks for your help, I am trying to build SLEDGE platform, this is on Ubuntu, this is running  ./install_deb.sh command is the problem.Looking forward to your help, thanks!

**Comment by emil916** [comment]
It looks like LLVM has not provided a version=12 package for Ubuntu 22 LTS. At this point I would recommend to change the LLVM_VERSION in that bash script to 13 and try again.

Kindly let know how it goes.

**Comment by YlqyY** [comment]
> It looks like LLVM has not provided a version=12 package for Ubuntu 22 LTS. At this point I would recommend to change the LLVM_VERSION in that bash script to 13 and try again.
> 
> Kindly let know how it goes.

Thanks for your help, I changed LLVM_VERSION=12 in the install_deb.sh file as you reminded, I changed it to 13, then I ran the./iinstall_deb.sh command again, the following message appeared:
update-alternatives: Error: No candidate for llvm-config
update-alternatives: Error: No candidate for llvm-objdump
update-alternatives: Error: No candidate for llvm-objdump
update-alternatives: Use /usr/bin/clang-format-13 to provide /usr/bin/clang-format (clang-format) in automatic mode
update-alternatives: Use /usr/bin/clang-13 to provide /usr/bin/clang (clang) in automatic mode
update-alternatives: Use /usr/bin/clang++-13 to provide /usr/bin/clang++ (clang++) in automatic mode.
update-alternatives: Error: alternative path /usr/bin/llvm-config-13 doesn't exist
update-alternatives: Error: alternative path /usr/bin/llvm-objdump-13 doesn't exist
update-alternatives: Use /usr/bin/clang-tidy-13 to provide /usr/bin/clang-tidy (clang-tidy) in automatic mode
update-alternatives: Error: alternative path /usr/bin/wasm-ld-13 doesn't exist
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12) Info: Latest Update on 2022-12-15, Rust Version 1.66.0 (69F9c33d7 2022-12-12)
info: component 'rust-std' for target 'wasm32-wasi' is up to date
info: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is up to date
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

Looking forward to your help, thanks!

**Comment by emil916** [comment]
You trying this with sudo or without? 

And what is the result of running the following command (again with sudo if necessary)?
curl --proto '=https' --tlsv1.2 -sSf https://apt.llvm.org/llvm.sh | bash -s -- 13

**Comment by YlqyY** [comment]
> 你尝试这个有还是没有？`sudo `
> 
> 运行以下命令的结果是什么（如有必要，再次运行）？`sudo ` `curl --proto '=https' --tlsv1.2 -sSf https://apt.llvm.org/llvm.sh | bash -s -- 13`



> 你尝试这个有还是没有？`sudo `
> 
> 运行以下命令的结果是什么（如有必要，再次运行）？`sudo ` `curl --proto '=https' --tlsv1.2 -sSf https://apt.llvm.org/llvm.sh | bash -s -- 13`
