### ISSUE TITLE
Track Time Waiting for Locks

### ISSUE THREAD

**Issue by bushidocodes** [gwsystems/sledge-serverless-framework#82]
Places where runtime faces lock contention:
* spins in ck_spinlock_fas_lock, called by priority_queue_length, priority_queue_enqueue, priority_queue_delete
* These are called by local_runqueue_minheap_add, global_request_scheduler_minheap_add, local_runqueue_minheap_delete

What about trylock?

**Comment by emil916** [comment]
Looking at the current global runqueue lock-tracking instrumentation, feels like the results printed do not make sense.  Here is my expectations of a lock-tracker:

For each of the various locks we have in the system (global_runqueue lock, perf_window lock, persistence lock and so on)
- How long did the total locking take in the system overall? (sum of all [lock~unlock] periods over the total runtime)
- How long did the longest [lock~unlock] period last throughout the total runtime? What function was it in?
- Per worker and listener, how long did the total locking take overall? 
- Per worker and listener, how long did the longest locking period take overall? What function was it in?
